---

- hosts: all
  become: true
  pre_tasks:

  - name: update ubuntu cache
    apt:
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

- hosts: controller
  roles:
    - neutron
    - horizon
    - cinder

- hosts: compute
  roles:
    - neutron
    - horizon
    - cinder
