---

- name: install Horizon
  apt:
    name:
      - openstack-dashboard
      - apache2
    state: present
  become: true

- name: restart apache2
  service:
    name: apache2
    state: restarted
    enabled: yes
  become: true
